### ISSUE TITLE
Need support listing map type and region 

### ISSUE THREAD

**Issue by Yus147** [vvquocanh/seproject2020#17]
We all agreed that the main player will start off on a beach side area, now we need to decide how the main map layout look like. where the village will be and how we should continue from said village.
I was gonna finish the tileset before working on the layout, but seem like the other way around is way more optimal.
To help please post your map layout in the comment. You can use what ever you want to draw the map. I can work on it as soon as we decide on the layout.
@vvquocanh @lethuckien

**Comment by lethuckien** [comment]
![Map Layout](https://user-images.githubusercontent.com/59216515/79709601-ce1b2680-82ec-11ea-96ff-10ddbf39e0c2.png)
Here is the map layout

**Comment by Yus147** [comment]
@lethuckien Can you specify where which enemy type will be on the map. Also can you section the map more clearly
Thanks

**Comment by Yus147** [comment]
@vvquocanh I still need your idea on how the map should be and your opinion on @lethuckien 's map

**Comment by Yus147** [comment]
Seem like we will go with this map design
