### ISSUE TITLE
Finish the rest of the tilemaps 

### ISSUE THREAD

**Issue by vvquocanh** [vvquocanh/seproject2020#7]
Create the first map

**Comment by Yus147** [comment]
Have some problem with tree sprites, need further learning

**Comment by Yus147** [comment]
@vvquocanh @lethuckien 
Should the tilemap 

- [ ] Have Outline
![Have Outline](https://user-images.githubusercontent.com/59216915/79677366-bd9a7b80-821a-11ea-9fd0-5764e1892847.png)

- [ ] No outline

![No Outline](https://user-images.githubusercontent.com/59216915/79677368-becba880-821a-11ea-87ea-7cfc53e48773.png)

**Comment by vvquocanh** [comment]
I think have outline is better
